FundsApplication/FundsApplication/Models/Fund.cs
using FundsApplication.HelpClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FundsApplication.Models
{
    public class Fund
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal LatestValue { get; set; }


        public Fund()
        {

        }

        public Fund(int id,string name,string description,decimal latestValue)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.LatestValue = latestValue;
        }

        public Fund(RandomFund randFund)
        {
            this.Name = randFund.Name;
            this.Description = randFund.Description;
        }

    }
}

FundsApplication/FundsApplication/Models/Value.cs
using FundsApplication.HelpClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FundsApplication.Models
{
    public class Value
    {
        public int Id { get; set; }
        public int FundId { get; set; }
        public DateTime Date { get; set; }
        public decimal FundValue { get; set; }

        public Value()
        {

        }
        public Value(int id,int fundId,DateTime date,decimal fundValue)
        {
            this.Id = id;
            this.FundId = fundId;
            this.Date = date;
            this.FundValue = fundValue;
        }

        public Value(RandomValue randValue)
        {
            this.FundId = randValue.FundId;
            this.Date = randValue.Date;
            this.FundValue = randValue.FundValue;
        }
    }
}

FundsApplication/FundsApplication/Controllers/FundController.cs
using FundsApplication.Database;
using FundsApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FundsApplication.Controllers
{
    public class FundController : Controller
    {
        
        int _selectedPage = 1;
        int _rowsCount = 0;
        int _pagesCount = 0;

        List<Fund> _foundsList = new List<Fund>();
        List<Value> _details = new List<Value>();

        DatabaseLogic _databaseLogic = new DatabaseLogic(new DatabaseConnection());

        static string _searchValue = "";


        #region Index View

        public ActionResult Index(string fundName,int selectedPage = 1)
        {
            //INFO:: Uncomment line below on FIRST RUN !!
           // _databaseLogic.InsertMillionData();

            if (fundName != _searchValue) { selectedPage = 1; }

            _selectedPage = selectedPage;
            _searchValue = fundName;
            _foundsList = GetTenFounds(fundName);

            var tupleData = new Tuple<IEnumerable<Fund>,int[]>(_foundsList, new int[] { _rowsCount, _pagesCount });
            return View(tupleData);
        }

        List<Fund> GetTenFounds(string fundName)
        {          
            _foundsList = _databaseLogic.GetDataWithName(fundName,_selectedPage);
            SetDropdown();
            return _foundsList;
        }

        void SetDropdown()
        {

            int pageCount = (PagesCount(_searchValue));
            var Values = SetDropdownRange(pageCount);
            var aList = Values.Select((x, i) => new { Value = x, Data = x }).ToList();            
            ViewBag.PageNums = new SelectList(aList, "Value", "Data", _selectedPage);        
        }

        int PagesCount(string fundName)
        {
            int pageCount = 0;
            pageCount = _databaseLogic.GetFundCount(fundName);
            _rowsCount = pageCount;
            pageCount = (pageCount % 10) == 0 ? pageCount / 10 : (pageCount / 10) + 1;
            _pagesCount = pageCount;

            return pageCount;
        }

        int[] SetDropdownRange(int pageCount)
        {
            int i = (_selectedPage > 5) ? (_selectedPage - 4) : 1;
            i = (i + 9) > pageCount ? (pageCount - 8) : i;

            int j = pageCount > 9 ? 9 : pageCount;          
            i = j < 5 ? pageCount - 9 : i;
            i = i < 1 ? 1 : i;

            return Enumerable.Range(i,j).ToArray();
        }


        #endregion

        #region DetailsView

        public ActionResult Details(int? id, string name, string description)
        {
            _details = GetDetails((int)id);
            var tupleData = new Tuple<IEnumerable<Value>, string, string>(_details, name, description);
            return View(tupleData);
        }

        public List<Value> GetDetails(int fundId)
        {
            return _databaseLogic.GetDetails(fundId);
        }

        #endregion
    }
}

FundsApplication/FundsApplication/Views/Fund/Details.cshtml
@model Tuple<IEnumerable<FundsApplication.Models.Value>,string,string>
@{
    ViewBag.Title = "Details";
}

<br/>
<center>
    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Name: @Model.Item2 </th>
            <th>Description: @Model.Item3</th>
        </tr>
    </table>

    <h2>Details</h2>

    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Date</th>
            <th>Value</th>
        </tr>
        @if (Model.Item1 != null)
        {
            foreach (var d in Model.Item1)
            {


                <tr>
                    <td>@d.Date</td>
                    <td>@d.FundValue</td>
                </tr>

            }
        }
    </table>
 </center>

FundsApplication/FundsApplication/Views/Fund/Index.cshtml
@model Tuple<IEnumerable<FundsApplication.Models.Fund>, int[]>
@{
    ViewBag.Title = "Index";
}


@using (Html.BeginForm("Index", "Fund", FormMethod.Post))
{
    <center>
        
        <p><font size="18">Founds</font></p>
    </center>

    <center>
        @Html.TextBox("fundName", "", new { placeholder = "Enter Fund Name..." })


        page:
        
        @Html.DropDownList("selectedPage", (SelectList)ViewBag.PageNums)
        <br />
        <input type="submit" value="Search" />
        



    </center>
    <br /><br /><br /><hr/>

}

Rows: @Model.Item2[0]   Pages: @Model.Item2[1]
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Value</th>

    </tr>
    @if (Model.Item1 != null)
    {
        foreach (var d in Model.Item1)
        {


            <tr>
                <td>@d.Name</td>
                <td>@d.Description</td>
                <td>@d.LatestValue</td>
                <td>@Html.ActionLink("Details", "Details", new { id = d.Id, name = d.Name, description = d.Description }) </td>
            </tr>

        }
    }
</table>

FundsApplication/FundsApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FundApplication", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>